name: _service_layer
description: Service Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _domain_layer:
    path: ../_domain_layer
    
  faker: ^2.1.0

  flutter:
    sdk: flutter

  freezed_annotation: ^2.2.0
  riverpod: ^2.1.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  
  flutter_test:
    sdk: flutter

  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mockito: ^5.3.2

flutter:
