name: flutter_layered_template_contacts_example
description: Flutter Layered Template contacts example with sync and async APIs.

publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.3.2
  freezed_annotation: ^2.2.0
  go_router: ^6.2.0
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  json_annotation: ^4.8.0
  meta: ^1.8.0
  quiver: ^3.2.1
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  isar_generator: ^3.0.5
  json_serializable: ^6.6.1
  mockito: ^5.3.2
        
flutter:
  uses-material-design: true
