name: _domain_layer
description: Domain Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
    
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  meta: ^1.8.0
  riverpod: ^2.1.3
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mockito: ^5.3.2

flutter:
