name: _core_layer
description: Core Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: any

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
    
flutter:
