name: _presentation_layer
description: Presentation Layer Package

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  _core_layer:
    path: ../_core_layer
  _domain_layer:
    path: ../_domain_layer
    
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: any
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
